export const empathy_stories = [
    {
        id: 1,
        title: "Dollar Tree store",
        description_short: "Stella came with her mom into a store that everything is only one dollar...",
        description_long: "<p>Stella came with her mom into a store that everything is only one dollar. Her first reaction at the beginning was ‘Wow, it is so cheap, I am gonna get everything!’</p><p>She browsed around the office supply area to get some pencils. She was also really craving for some candies. Her basket of stuff is getting more full until someone yelled at her in the back ‘Stella, you are crazy, do you need all of them?’ That was her mom’s voice, definitely not a calming tone at that moment.</p><p>Her mom took a moment to breath and decided to take her to the counter for check out, regardless of an almost overflow basket she was trying to carry.</p><p’>$99, cash or credit?’ - the cashier summed up. Stella stared at her mom: ‘Mom, why is it that much? I thought everything is just one dollar?’.</p><p>Her mom gave her a hug and explained: ‘honey, each item is one dollar but if you just keep adding them without thinking, it can be a lot. When you have not made money, you need to even appreciate every dollar even more, do you get it?’</p><p>Stella nodded and replied: ‘yes, I got it, I am sorry for being greedy and for not caring of money’. Then she came back to the cashier to ask: ‘excuse me, can I put back some of the items I do not need?’. The cashier was smiling: ‘Of course, sweetie’</p>",
        thumbnail: "https://www.clipartmax.com/png/middle/422-4227601_dollar-store-products-from-vineland-syrup-dollar-store-transparent.png" 
    },
    {
        id: 2,
        title: "Lineal",
        description_short: "Lineal is the only guard who takes care of the ranch...",
        description_long: "<p>This morning, Suju wanted to walk out of her house, she wanted new wind. After considering, she picked up her bike and did a free ride around the neighborhood. Suddenly, she remembered one time visiting a ranch nearby but had not got to take a closer look at it.  She then decided to find her way back there. </p><p>She walked slowly around the area, it was the same curiosity about who owns this land and what this is for. Perhaps it is for wedding ceremony but is it? </p><p>She then saw an old man watering flowers, she stepped forward to him. </p><p>“Excuse me, are you living here?”</p><p>The man turned his back, smiled, and replied: “Yes, I am, I am in charge of taking care of this place”</p><p>Then he continued: “Do you have a wedding coming up?”</p><p>She was startled: “Oh no, I am too young for that. I am just exploring”</p><p>“I see, then welcome, you must be new here, this is a wedding venue” - the man replied. </p><p>Suju felt a sense of familiarity by interacting with him. She asked him about where he is from and she got to know that he is Lineal, a Mexican who has been living in the United States for 26 years already. He shared that he has got a good time here and he appreciated the job opportunity he is having. His boss is the one who owns this wedding venue and they have him take care of the plants and flowers as well as the properties. Every day that is his job, waking up and watching at the nature, making sure the grasses are still green. </p><p>Perhaps, to some people, it is a boring and repetitive job. However, to him, that seems like a joy. He is happy to do so. He was also very excited to show Suju around. He drove her on something that looks like a golf buggy. </p><p>Somewhere there is someone around you, who appreciate little things they have everyday. To them, life is beautiful.</p>",
        thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT72exheX0ukejho9kJBPm02P-2g8X459TdOUB9eKq2WMnBDBkLN-V3sOcnD8hMc_jyo88&usqp=CAU" 
    },
    {
        id: 3,
        title: "A female biker finished 36 miles",
        description_short: "Biking, to Kim, is a free wheel activity. She gets to explore places and enjoys the wind...",
        description_long: "<p>Biking, to Kim, is a free wheel activity. She gets to explore places and enjoys the wind. </p><p>However, she has never got a really good bike to venture far. She recently lost her bike and her friend was kind enough to lend her one. This new bike looks very feminine, it is not a mountain bike nor a road bike, but she learnt to accept that it is hers now. </p><p>She biked to get her groceries. Sometimes, she wondered if it were ever broken on the road because two bags of groceries were too heavy. Sometimes, she wondered if the bike could stand if she goes in a longer distance. </p><p>That day finally came. She decided to give it a try. She insisted to cross the 15 mile bridge that locates 5 miles away from her house. It came without any preparation. She just took the bike, some nut snacks, water, and started her journey. </p><p>The first mile was light and easy. The trail from her house is a nice long path that leads to an open space eventually. She biked and biked, she never actually cared if she would make it to the point she imagined. That is beauty of the journey. Her path embraces around a canal. </p><p>It was good to say Hi to other bikers. On the other side of the canal, people were also enjoying the move. It was hard to say whether they ever got tired. </p><p>The more she biked, the more she could feel her body getting tired. In the meantime, she was not sure if stopping was a solution. Perhaps, the bay in front of her and the biker’s high as well as the welcome from other bikers were what keep her move forward. She thought it was okay to go a bit slower, or to go with the flow and without forcing. </p><p>Going up the hill and going against the wind were extremely challenging. Nevertheless, she accepted that she is limited, that it is okay to stop at some points, to even not finish up if her mind and her physical strength do not align. </p><p>Being impatient is normal in a journey. When she was in the middle, she always looked forward to the end. Although, she did not want to miss out the scenery by wanting too much to finish. There were many times in which she wanted to turn but she was curious what if she kept running, and these many times were what carried her to the end. </p><p>When she reached Palo Alto, she did not forget to smile, and to appreciate her effort. Yet she was a bit uncertain about the way going back. She could feel her bones. Then she let the pain aside to roam around the little town. </p><p>On the way back, stopping was not a choice anymore, she needed to get home before it got dark. And she made it finally, one way was not easier than the other. She was very proud of herself for the commitment and all of the effort. </p><p>It was not just about ‘just do it’, it is also about do it and keep doing it, till you are at the finish point and never regret when looking back. </p>",
        thumbnail: "https://media.istockphoto.com/vectors/riding-a-bicycle-vector-id165670255?k=20&m=165670255&s=612x612&w=0&h=COxALPHxtKp9GlCC0vVIGm0M1j6AmllgwDzUaWnkZRs=" 
    },
    {
        id: 4,
        title: "A female biker finished 36 miles",
        description_short: "Stella came with her mom into a store that everything is only one dollar...",
        description_long: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>",
        thumbnail: "https://media.istockphoto.com/vectors/riding-a-bicycle-vector-id165670255?k=20&m=165670255&s=612x612&w=0&h=COxALPHxtKp9GlCC0vVIGm0M1j6AmllgwDzUaWnkZRs=" 
    }
]